# Site settings
title: WfCommons
subtitle: "Community Framework for Enabling Scientific Workflow Research and Development"

markdown: kramdown
enable-mathjax: yes

permalink: /blog/:title/

# scholar
scholar:
  sort_by: author
  group_by: year
  group_order: descending
  type_order: [article, inproceedings, phdthesis, techreport]
  bibliography_template: bib
  reference_template: bib

# Collections
collections:
  research:
    output: true
    permalink: /research/:path/

plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.

exclude:
  - .jekyll-cache
  - .idea
  - README.md
  - LICENSE
