#!/usr/bin/env python3
"""Regenerate _data/traces.yml from the WfCommons/WfInstances GitHub repository.

Queries the GitHub git-trees API (no cloning) and counts, for each top-level
workflow-system directory:
  - traces:       number of .json instance files anywhere under the directory
  - applications: number of distinct workflow applications

Applications are inferred as follows: after ignoring structural directories
("legacy", "ro-crate"), the first directory component under the system is the
application; for instance files not inside an application directory, the
filename prefix up to the first "-" is used (e.g. "airrflow-dirt02-001.json"
-> "airrflow").

Usage:  python3 scripts/update_instances.py
Environment:  GITHUB_TOKEN (optional) raises the API rate limit.
"""

import json
import os
import sys
import urllib.request

REPO = "wfcommons/WfInstances"
BRANCH = "main"
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "_data", "traces.yml")

# Directory levels that group instances but are not applications themselves.
STRUCTURAL_DIRS = {"legacy", "ro-crate"}

# Proper display names for workflow systems (fallback: capitalized dir name).
DISPLAY_NAMES = {
    "makeflow": "Makeflow",
    "nextflow": "Nextflow",
    "pegasus": "Pegasus",
    "snakemake": "Snakemake",
    "streamflow": "StreamFlow",
    "helloworld": "Hello World",
}


def fetch_tree():
    url = f"https://api.github.com/repos/{REPO}/git/trees/{BRANCH}?recursive=1"
    request = urllib.request.Request(url)
    request.add_header("Accept", "application/vnd.github+json")
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(request, timeout=60) as response:
        data = json.load(response)
    if data.get("truncated"):
        sys.exit("error: GitHub tree listing was truncated; refusing to write partial counts")
    return data["tree"]


def application_name(parts):
    """Return the application name for a path split like [system, ..., file.json]."""
    inner = [p for p in parts[1:-1] if p not in STRUCTURAL_DIRS]
    if inner:
        return inner[0]
    filename = parts[-1][: -len(".json")]
    return filename.split("-")[0]


def collect(tree):
    systems = {}
    for entry in tree:
        if entry["type"] != "blob" or not entry["path"].endswith(".json"):
            continue
        parts = entry["path"].split("/")
        if len(parts) < 2 or parts[0].startswith("."):
            continue
        system = systems.setdefault(parts[0], {"traces": 0, "apps": set()})
        system["traces"] += 1
        system["apps"].add(application_name(parts))
    return systems


def write_yaml(systems):
    lines = [
        "# AUTO-GENERATED by scripts/update_instances.py from",
        f"# https://github.com/{REPO} — do not edit by hand.",
        "",
    ]
    ordered = sorted(systems.items(), key=lambda kv: (-kv[1]["traces"], kv[0]))
    for name, info in ordered:
        display = DISPLAY_NAMES.get(name, name.capitalize())
        lines += [
            f"- name: {display} Execution Instances",
            f"  website: https://github.com/{REPO}/tree/{BRANCH}/{name}",
            f"  applications: {len(info['apps'])}",
            f"  traces: {info['traces']}",
            "",
        ]
    with open(OUTPUT, "w") as f:
        f.write("\n".join(lines))


def main():
    systems = collect(fetch_tree())
    if not systems:
        sys.exit("error: no instance files found; refusing to write empty traces.yml")
    write_yaml(systems)
    total = sum(s["traces"] for s in systems.values())
    apps = set().union(*(s["apps"] for s in systems.values()))
    print(f"wrote {os.path.normpath(OUTPUT)}: {len(systems)} collections, "
          f"{total} instances, {len(apps)} distinct applications")


if __name__ == "__main__":
    main()
